from munch import Munch

config = {
    'num_classes': 52,
    'index_gt': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                 50, 51],  # 51
    'schema': 1,  # train bs/mesh/hd 54
    # 'schema': 1,  # train f
    'input_size': 224,
    'width_mult': 1,
    'output_c': 256,
    'global_step': 1,
    'exp_dir': r'/data/llf/exp/schema_0_224_256_1.0_51_f',
    'ckpt': '/app/checkpoints/iteration_432000.pt',
    # 'ckpt': '',
    'finetune': False,
    'lr': 0.0002,
    'scheduler_gamma': 0.955,
    'batch_size': 128,
    'workers': 8,
    'steps': 2000000,
    'lr_steps': 4000,
    'l1_loss': 1.0,
    'cfg_loss': 1.0,
    'mesh_loss': 3.0,
    'head_loss': 2.0,
    'tongueout_loss': 1.0,
    'tonguemove_loss': 1.0,
    'log_interval': 20,
    'val_or_not': False,
    'val_interval': 4000,
    # 'train_data': [
    #     '/data/llf/train/1',
    #     '/data/llf/train/2',
    #     '/data/llf/train/3',
    #     '/data/llf/train/4',
    #     '/data/llf/train/6',
    #     '/data/llf/train/7',
    #     '/data/llf/train/8',
    #     '/data/llf/train/10',
    #     '/data/llf/train/bg',
    #     '/data/llf/train/bg',
    #     '/data/llf/train/bg',
    #     '/data/llf/train/cheekpuff',
    #     '/data/llf/train/tongue',
    #     '/data/llf/train/wink',
    #     '/data/llf/train/sad',
    #     '/data/llf/train/cheekpuff1',
    #     '/data/llf/train/tongue1',
    #     '/data/llf/train/wink1',
    #     '/data/llf/train/sad1',
    #     '/data/llf/train/reall_data/lzy_3', '/data/llf/train/reall_data/ysj_4',
    #     '/data/llf/train/reall_data/mxp_16', '/data/llf/train/reall_data/zwm_1',
    #     '/data/llf/train/reall_data/ys_4', '/data/llf/train/reall_data/lz_0',
    #     '/data/llf/train/reall_data/hsn_6', '/data/llf/train/reall_data/cf_10',
    #     '/data/llf/train/reall_data/czf_12', '/data/llf/train/reall_data/pgl_12',
    #     '/data/llf/train/reall_data/xj_10', '/data/llf/train/reall_data/lz_1',
    #     '/data/llf/train/reall_data/zb_3',
    #     '/data/llf/train/reall_data/lzh_5', '/data/llf/train/reall_data/ljj_0',
    #     '/data/llf/train/reall_data/pgl_11', '/data/llf/train/reall_data/lzh_7',
    #     '/data/llf/train/reall_data/czf_2', '/data/llf/train/reall_data/wzj_1',
    #     '/data/llf/train/reall_data/lzy_14', '/data/llf/train/reall_data/cb_9',
    #     '/data/llf/train/reall_data/zwm_15', '/data/llf/train/reall_data/wzj_15',
    #     '/data/llf/train/reall_data/fjb_16', '/data/llf/train/reall_data/ljj_9',
    #     '/data/llf/train/reall_data/cf_14', '/data/llf/train/reall_data/xjj_11',
    #     '/data/llf/train/reall_data/zhf_12', '/data/llf/train/reall_data/xl_0',
    #     '/data/llf/train/reall_data/xjj_3', '/data/llf/train/reall_data/lzh_14',
    #     '/data/llf/train/reall_data/zq_6', '/data/llf/train/reall_data/xl_7',
    #     '/data/llf/train/reall_data/cf_8', '/data/llf/train/reall_data/cf_2',
    #     '/data/llf/train/reall_data/ysj_3', '/data/llf/train/reall_data/xyf_14',
    #     '/data/llf/train/reall_data/zyc_17', '/data/llf/train/reall_data/pgl_10',
    #     '/data/llf/train/reall_data/zb_7', '/data/llf/train/reall_data/xl_15',
    #     '/data/llf/train/reall_data/xjj_7', '/data/llf/train/reall_data/hsn_3',
    #     '/data/llf/train/reall_data/pgl_1', '/data/llf/train/reall_data/zwm_14',
    #     '/data/llf/train/reall_data/fjb_1', '/data/llf/train/reall_data/lzy_15',
    #     '/data/llf/train/reall_data/xjj_5', '/data/llf/train/reall_data/ysj_6',
    #     '/data/llf/train/reall_data/zhf_1', '/data/llf/train/reall_data/wzj_6',
    #     '/data/llf/train/reall_data/fjb_17', '/data/llf/train/reall_data/lzh_0',
    #     '/data/llf/train/reall_data/hsn_0', '/data/llf/train/reall_data/zhf_8',
    #     '/data/llf/train/reall_data/fjb_7', '/data/llf/train/reall_data/zhf_2',
    #     '/data/llf/train/reall_data/fzy_7', '/data/llf/train/reall_data/lz_11',
    #     '/data/llf/train/reall_data/cb_7', '/data/llf/train/reall_data/czf_8',
    #     '/data/llf/train/reall_data/xyf_13', '/data/llf/train/reall_data/xj_0',
    #     '/data/llf/train/reall_data/ys_3', '/data/llf/train/reall_data/zh_1',
    #     '/data/llf/train/reall_data/cf_0', '/data/llf/train/reall_data/hsn_2',
    #     '/data/llf/train/reall_data/zhf_13', '/data/llf/train/reall_data/zq_9',
    #     '/data/llf/train/reall_data/zh_10', '/data/llf/train/reall_data/cb_5',
    #     '/data/llf/train/reall_data/cf_16', '/data/llf/train/reall_data/zb_8',
    #     '/data/llf/train/reall_data/zb_15', '/data/llf/train/reall_data/pgl_6',
    #     '/data/llf/train/reall_data/pgl_9', '/data/llf/train/reall_data/xyf_11',
    #     '/data/llf/train/reall_data/zhf_17', '/data/llf/train/reall_data/cf_6',
    #     '/data/llf/train/reall_data/ysj_2', '/data/llf/train/reall_data/xl_10',
    #     '/data/llf/train/reall_data/cf_3', '/data/llf/train/reall_data/cb_6',
    #     '/data/llf/train/reall_data/xl_4', '/data/llf/train/reall_data/fjb_0',
    #     '/data/llf/train/reall_data/zq_1', '/data/llf/train/reall_data/zyc_12',
    #     '/data/llf/train/reall_data/zhf_7', '/data/llf/train/reall_data/cb_11',
    #     '/data/llf/train/reall_data/lzh_11', '/data/llf/train/reall_data/zh_13',
    #     '/data/llf/train/reall_data/cf_12', '/data/llf/train/reall_data/xl_6',
    #     '/data/llf/train/reall_data/ys_0', '/data/llf/train/reall_data/xl_1',
    #     '/data/llf/train/reall_data/zwm_3', '/data/llf/train/reall_data/xyf_4',
    #     '/data/llf/train/reall_data/fzy_12', '/data/llf/train/reall_data/ljj_6',
    #     '/data/llf/train/reall_data/fzy_13', '/data/llf/train/reall_data/zq_15',
    #     '/data/llf/train/reall_data/wzj_9', '/data/llf/train/reall_data/ysj_7',
    #     '/data/llf/train/reall_data/xj_7', '/data/llf/train/reall_data/lzy_12',
    #     '/data/llf/train/reall_data/mxp_6', '/data/llf/train/reall_data/zb_5',
    #     '/data/llf/train/reall_data/xj_14', '/data/llf/train/reall_data/xj_12',
    #     '/data/llf/train/reall_data/zq_17', '/data/llf/train/reall_data/fjb_13',
    #     '/data/llf/train/reall_data/lzh_6', '/data/llf/train/reall_data/xl_9',
    #     '/data/llf/train/reall_data/zh_15', '/data/llf/train/reall_data/hsn_11',
    #     '/data/llf/train/reall_data/ys_2', '/data/llf/train/reall_data/zb_4',
    #     '/data/llf/train/reall_data/ys_11', '/data/llf/train/reall_data/zwm_2',
    #     '/data/llf/train/reall_data/lz_7', '/data/llf/train/reall_data/xl_16',
    #     '/data/llf/train/reall_data/fjb_14', '/data/llf/train/reall_data/lzy_0',
    #     '/data/llf/train/reall_data/czf_14', '/data/llf/train/reall_data/lzy_7',
    #     '/data/llf/train/reall_data/zyc_3', '/data/llf/train/reall_data/xjj_15',
    #     '/data/llf/train/reall_data/wzj_5', '/data/llf/train/reall_data/zb_2',
    #     '/data/llf/train/reall_data/xj_9', '/data/llf/train/reall_data/hsn_15',
    #     '/data/llf/train/reall_data/pgl_3', '/data/llf/train/reall_data/zh_4',
    #     '/data/llf/train/reall_data/xjj_13', '/data/llf/train/reall_data/zyc_6',
    #     '/data/llf/train/reall_data/ljj_3', '/data/llf/train/reall_data/xj_13',
    #     '/data/llf/train/reall_data/zyc_10', '/data/llf/train/reall_data/lz_4',
    #     '/data/llf/train/reall_data/lz_16', '/data/llf/train/reall_data/xjj_0',
    #     '/data/llf/train/reall_data/hsn_16', '/data/llf/train/reall_data/zyc_0',
    #     '/data/llf/train/reall_data/lzy_10', '/data/llf/train/reall_data/ljj_8',
    #     '/data/llf/train/reall_data/xjj_14', '/data/llf/train/reall_data/wzj_11',
    #     '/data/llf/train/reall_data/zb_12', '/data/llf/train/reall_data/ljj_4',
    #     '/data/llf/train/reall_data/fzy_2', '/data/llf/train/reall_data/zq_7',
    #     '/data/llf/train/reall_data/pgl_7', '/data/llf/train/reall_data/ysj_13',
    #     '/data/llf/train/reall_data/lzh_10', '/data/llf/train/reall_data/zhf_11',
    #     '/data/llf/train/reall_data/zh_16', '/data/llf/train/reall_data/xl_14',
    #     '/data/llf/train/reall_data/lzy_6', '/data/llf/train/reall_data/zyc_2',
    #     '/data/llf/train/reall_data/zyc_15', '/data/llf/train/reall_data/ljj_7',
    #     '/data/llf/train/reall_data/mxp_14', '/data/llf/train/reall_data/xl_12',
    #     '/data/llf/train/reall_data/xjj_8', '/data/llf/train/reall_data/xyf_1',
    #     '/data/llf/train/reall_data/xj_5', '/data/llf/train/reall_data/xyf_0',
    #     '/data/llf/train/reall_data/xyf_10', '/data/llf/train/reall_data/ys_12',
    #     '/data/llf/train/reall_data/cf_11', '/data/llf/train/reall_data/fjb_6',
    #     '/data/llf/train/reall_data/lzy_11', '/data/llf/train/reall_data/pgl_8',
    #     '/data/llf/train/reall_data/ljj_5', '/data/llf/train/reall_data/fjb_5',
    #     '/data/llf/train/reall_data/cb_13', '/data/llf/train/reall_data/lz_17',
    #     '/data/llf/train/reall_data/xjj_9', '/data/llf/train/reall_data/zq_16',
    #     '/data/llf/train/reall_data/zq_8', '/data/llf/train/reall_data/lz_5',
    #     '/data/llf/train/reall_data/lz_9', '/data/llf/train/reall_data/xj_8',
    #     '/data/llf/train/reall_data/zb_1', '/data/llf/train/reall_data/xjj_17',
    #     '/data/llf/train/reall_data/fzy_10', '/data/llf/train/reall_data/pgl_4',
    #     '/data/llf/train/reall_data/xyf_8', '/data/llf/train/reall_data/zq_12',
    #     '/data/llf/train/reall_data/cf_7', '/data/llf/train/reall_data/cf_4',
    #     '/data/llf/train/reall_data/ljj_2', '/data/llf/train/reall_data/wzj_3',
    #     '/data/llf/train/reall_data/zh_14', '/data/llf/train/reall_data/zhf_3',
    #     '/data/llf/train/reall_data/czf_11', '/data/llf/train/reall_data/wzj_13',
    #     '/data/llf/train/reall_data/mxp_8', '/data/llf/train/reall_data/czf_10',
    #     '/data/llf/train/reall_data/cb_10', '/data/llf/train/reall_data/zhf_4',
    #     '/data/llf/train/reall_data/hsn_8', '/data/llf/train/reall_data/czf_13',
    #     '/data/llf/train/reall_data/lzy_17', '/data/llf/train/reall_data/lz_3',
    #     '/data/llf/train/reall_data/mxp_13', '/data/llf/train/reall_data/ys_5',
    #     '/data/llf/train/reall_data/wzj_14', '/data/llf/train/reall_data/zwm_13',
    #     '/data/llf/train/reall_data/hsn_13', '/data/llf/train/reall_data/zh_12',
    #     '/data/llf/train/reall_data/pgl_15', '/data/llf/train/reall_data/zhf_16',
    #     '/data/llf/train/reall_data/czf_7', '/data/llf/train/reall_data/lzy_9',
    #     '/data/llf/train/reall_data/hsn_17', '/data/llf/train/reall_data/fzy_17',
    #     '/data/llf/train/reall_data/lzh_1', '/data/llf/train/reall_data/zb_16',
    #     '/data/llf/train/reall_data/ljj_1', '/data/llf/train/reall_data/fjb_2',
    #     '/data/llf/train/reall_data/xl_8', '/data/llf/train/reall_data/zyc_1',
    #     '/data/llf/train/reall_data/fzy_9', '/data/llf/train/reall_data/czf_0',
    #     '/data/llf/train/reall_data/fzy_14', '/data/llf/train/reall_data/czf_4',
    #     '/data/llf/train/reall_data/wzj_7', '/data/llf/train/reall_data/fjb_15',
    #     '/data/llf/train/reall_data/fzy_4', '/data/llf/train/reall_data/ysj_11',
    #     '/data/llf/train/reall_data/zwm_16', '/data/llf/train/reall_data/ysj_14',
    #     '/data/llf/train/reall_data/wzj_16', '/data/llf/train/reall_data/zq_2',
    #     '/data/llf/train/reall_data/pgl_16', '/data/llf/train/reall_data/wzj_17',
    #     '/data/llf/train/reall_data/zh_3', '/data/llf/train/reall_data/fzy_3',
    #     '/data/llf/train/reall_data/zq_14', '/data/llf/train/reall_data/ysj_17',
    #     '/data/llf/train/reall_data/zhf_9', '/data/llf/train/reall_data/xl_13',
    #     '/data/llf/train/reall_data/cf_5', '/data/llf/train/reall_data/ys_6',
    #     '/data/llf/train/reall_data/xl_3', '/data/llf/train/reall_data/cf_9',
    #     '/data/llf/train/reall_data/zh_8', '/data/llf/train/reall_data/lzh_12',
    #     '/data/llf/train/reall_data/zyc_9', '/data/llf/train/reall_data/lz_8',
    #     '/data/llf/train/reall_data/fjb_4', '/data/llf/train/reall_data/ysj_16',
    #     '/data/llf/train/reall_data/zb_11', '/data/llf/train/reall_data/pgl_0',
    #     '/data/llf/train/reall_data/cb_14', '/data/llf/train/reall_data/cb_2',
    #     '/data/llf/train/reall_data/mxp_11', '/data/llf/train/reall_data/wzj_2',
    #     '/data/llf/train/reall_data/ys_16', '/data/llf/train/reall_data/mxp_1',
    #     '/data/llf/train/reall_data/xyf_7', '/data/llf/train/reall_data/lzh_4',
    #     '/data/llf/train/reall_data/lz_2', '/data/llf/train/reall_data/zhf_15',
    #     '/data/llf/train/reall_data/pgl_17', '/data/llf/train/reall_data/lzh_9',
    #     '/data/llf/train/reall_data/zb_6', '/data/llf/train/reall_data/fjb_8',
    #     '/data/llf/train/reall_data/cf_15', '/data/llf/train/reall_data/zb_10',
    #     '/data/llf/train/reall_data/ysj_8', '/data/llf/train/reall_data/hsn_4',
    #     '/data/llf/train/reall_data/ysj_1', '/data/llf/train/reall_data/xyf_6',
    #     '/data/llf/train/reall_data/xjj_16', '/data/llf/train/reall_data/zyc_4',
    #     '/data/llf/train/reall_data/zq_13', '/data/llf/train/reall_data/czf_5',
    #     '/data/llf/train/reall_data/zh_5', '/data/llf/train/reall_data/zq_11',
    #     '/data/llf/train/reall_data/zyc_7', '/data/llf/train/reall_data/fzy_15',
    #     '/data/llf/train/reall_data/lz_12', '/data/llf/train/reall_data/cb_3',
    #     '/data/llf/train/reall_data/pgl_14', '/data/llf/train/reall_data/lzy_8',
    #     '/data/llf/train/reall_data/mxp_2', '/data/llf/train/reall_data/zq_5',
    #     '/data/llf/train/reall_data/fjb_11', '/data/llf/train/reall_data/czf_9',
    #     '/data/llf/train/reall_data/zwm_0', '/data/llf/train/reall_data/ysj_0',
    #     '/data/llf/train/reall_data/ljj_12', '/data/llf/train/reall_data/lz_15',
    #     '/data/llf/train/reall_data/ljj_10', '/data/llf/train/reall_data/zb_17',
    #     '/data/llf/train/reall_data/lzy_4', '/data/llf/train/reall_data/mxp_3',
    #     '/data/llf/train/reall_data/czf_16', '/data/llf/train/reall_data/zq_3',
    #     '/data/llf/train/reall_data/lzh_2', '/data/llf/train/reall_data/zb_9',
    #     '/data/llf/train/reall_data/lzy_16', '/data/llf/train/reall_data/ysj_12',
    #     '/data/llf/train/reall_data/zb_13', '/data/llf/train/reall_data/lzh_3',
    #     '/data/llf/train/reall_data/cf_1', '/data/llf/train/reall_data/wzj_12',
    #     '/data/llf/train/reall_data/zyc_16', '/data/llf/train/reall_data/ljj_17',
    #     '/data/llf/train/reall_data/zhf_14', '/data/llf/train/reall_data/ys_10',
    #     '/data/llf/train/reall_data/zyc_14', '/data/llf/train/reall_data/zh_17',
    #     '/data/llf/train/reall_data/zhf_6', '/data/llf/train/reall_data/zyc_5',
    #     '/data/llf/train/reall_data/zh_9', '/data/llf/train/reall_data/ys_1',
    #     '/data/llf/train/reall_data/hsn_7', '/data/llf/train/reall_data/hsn_1',
    #     '/data/llf/train/reall_data/fjb_12', '/data/llf/train/reall_data/xj_11',
    #     '/data/llf/train/reall_data/xjj_2', '/data/llf/train/reall_data/zyc_8',
    #     '/data/llf/train/reall_data/fzy_11', '/data/llf/train/reall_data/ljj_15',
    #     '/data/llf/train/reall_data/pgl_5', '/data/llf/train/reall_data/hsn_14',
    #     '/data/llf/train/reall_data/ysj_5', '/data/llf/train/reall_data/hsn_12',
    #     '/data/llf/train/reall_data/wzj_8', '/data/llf/train/reall_data/ljj_11',
    #     '/data/llf/train/reall_data/mxp_0', '/data/llf/train/reall_data/zh_7',
    #     '/data/llf/train/reall_data/cb_1', '/data/llf/train/reall_data/cb_8',
    #     '/data/llf/train/reall_data/czf_1', '/data/llf/train/reall_data/xyf_5',
    #     '/data/llf/train/reall_data/xyf_9', '/data/llf/train/reall_data/lz_10',
    #     '/data/llf/train/reall_data/xl_11', '/data/llf/train/reall_data/mxp_10',
    #     '/data/llf/train/reall_data/zyc_11', '/data/llf/train/reall_data/zhf_5',
    #     '/data/llf/train/reall_data/xyf_3', '/data/llf/train/reall_data/mxp_7',
    #     '/data/llf/train/reall_data/ysj_9', '/data/llf/train/reall_data/fjb_9',
    #     '/data/llf/train/reall_data/zh_0', '/data/llf/train/reall_data/ysj_15',
    #     '/data/llf/train/reall_data/lzy_5', '/data/llf/train/reall_data/xjj_1',
    #     '/data/llf/train/reall_data/zb_14', '/data/llf/train/reall_data/wzj_0',
    #     '/data/llf/train/reall_data/xyf_12', '/data/llf/train/reall_data/mxp_5',
    #     '/data/llf/train/reall_data/zhf_0', '/data/llf/train/reall_data/hsn_10',
    #     '/data/llf/train/reall_data/fzy_1', '/data/llf/train/reall_data/ys_15',
    #     '/data/llf/train/reall_data/xj_3', '/data/llf/train/reall_data/lzy_13',
    #     '/data/llf/train/reall_data/cb_4', '/data/llf/train/reall_data/lz_14',
    #     '/data/llf/train/reall_data/fzy_8', '/data/llf/train/reall_data/mxp_4',
    #     '/data/llf/train/reall_data/cb_0', '/data/llf/train/reall_data/zq_4',
    #     '/data/llf/train/reall_data/lzy_1', '/data/llf/train/reall_data/fjb_10',
    #     '/data/llf/train/reall_data/zq_10', '/data/llf/train/reall_data/lzy_2',
    #     '/data/llf/train/reall_data/xj_1', '/data/llf/train/reall_data/wzj_10',
    #     '/data/llf/train/reall_data/xjj_10', '/data/llf/train/reall_data/lzh_16',
    #     '/data/llf/train/reall_data/wzj_4', '/data/llf/train/reall_data/cb_12',
    #     '/data/llf/train/reall_data/xjj_12', '/data/llf/train/reall_data/lz_6',
    #     '/data/llf/train/reall_data/xj_4', '/data/llf/train/reall_data/zh_6',
    #     '/data/llf/train/reall_data/ljj_14', '/data/llf/train/reall_data/xyf_2',
    #     '/data/llf/train/reall_data/fzy_6', '/data/llf/train/reall_data/ysj_10',
    #     '/data/llf/train/reall_data/lzh_13', '/data/llf/train/reall_data/xl_5',
    #     '/data/llf/train/reall_data/pgl_2', '/data/llf/train/reall_data/zq_0',
    #     '/data/llf/train/reall_data/zh_11', '/data/llf/train/reall_data/fzy_5',
    #     '/data/llf/train/reall_data/zhf_10', '/data/llf/train/reall_data/fjb_3',
    #     '/data/llf/train/reall_data/fzy_0', '/data/llf/train/reall_data/ys_9',
    #     '/data/llf/train/reall_data/lzh_15', '/data/llf/train/reall_data/fzy_16',
    #     '/data/llf/train/reall_data/czf_3', '/data/llf/train/reall_data/cf_13',
    #     '/data/llf/train/reall_data/ys_13', '/data/llf/train/reall_data/ys_14',
    #     '/data/llf/train/reall_data/pgl_13', '/data/llf/train/reall_data/czf_15',
    #     '/data/llf/train/reall_data/lzh_8', '/data/llf/train/reall_data/czf_6',
    #     '/data/llf/train/reall_data/mxp_15', '/data/llf/train/reall_data/mxp_17',
    #     '/data/llf/train/reall_data/xj_6', '/data/llf/train/reall_data/zb_0',
    #     '/data/llf/train/reall_data/xjj_4', '/data/llf/train/reall_data/zh_2',
    #     '/data/llf/train/reall_data/xj_2', '/data/llf/train/reall_data/ys_7',
    #     '/data/llf/train/reall_data/ljj_13', '/data/llf/train/reall_data/xl_2',
    #     '/data/llf/train/reall_data/zyc_13', '/data/llf/train/reall_data/hsn_9',
    #     '/data/llf/train/reall_data/ljj_16', '/data/llf/train/reall_data/xjj_6',
    #     '/data/llf/train/reall_data/lz_13', '/data/llf/train/reall_data/hsn_5',
    #     '/data/llf/train/reall_data/ys_8'
    # ],
    # 'train_data': ['/data/llf/train/fake_data/single_v1',
    #                '/data/llf/train/fake_data/single_v2',
    #                '/data/llf/train/fake_data/zb_4420_20_28',
    #                '/data/llf/train/fake_data/zb_4420_0_19'],
    'train_data': [
        '/data/llf/train/1',
        '/data/llf/train/2',
        '/data/llf/train/3',
        '/data/llf/train/4',
        '/data/llf/train/6',
        '/data/llf/train/7',
        '/data/llf/train/8',
        '/data/llf/train/10',
        '/data/llf/train/bg',
        '/data/llf/train/bg',
        '/data/llf/train/bg',
        '/data/llf/train/cheekpuff',
        '/data/llf/train/tongue',
    ],
    'test_data': [
        '/data/llf/train/val',

    ],
    # 'eval_ckpt': r'checkpoints\iteration_1408000.pt',
    'eval_ckpt': r'checkpoints/iteration_8000.pt',


}

cfg = Munch(config)
